plugins:
  nova-experiences:
    client: true
    default: false
  nova-experiences-date:
    client: true
    default: "Mar 12, 2017"
  nova-foodwaste:
    client: true
    default: false
  nova-foodwaste-date:
    client: true
    default: "Mar 12, 2017"
  nova-pollution:
    client: true
    default: false
  nova-pollution-date:
    client: true
    default: "Mar 12, 2017"
  nova-reading:
    client: true
    default: false
  nova-reading-date:
    client: true
    default: "Mar 12, 2017"
  nova-before-link:
    client: true
    default: "اتاق های"
  nova-link:
    client: true
    default: "نوآ"
  nova-after-link:
    client: true
    default: "وری"
  nova-foodwaste-link:
    client: true
    default: "/"
  nova-experiences-link:
    client: true
    default: "/"
  nova-pollution-link:
    client: true
    default: "/"
  nova-reading-link:
    client: true
    default: "/"
